spring:
  zuul:
    routes:
      myProduct:
        path: /myProduct/**
        serviceId: product
        sensitiveHeaders: #不对header进行过滤，达到转发携带cookie的目的
      #简洁写法
      #product: /myProduct/**
    ignored-patterns:  #避免被路由的写法
      - /**/product/listForOrder
  management:
    security:
      enabled: false